// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Ttk9YXF_HfHA1J5PrnwWgO7KmEMooFg',
    appId: '1:169765244214:web:37f309de65e4f078aef797',
    messagingSenderId: '169765244214',
    projectId: 'notifikasi-project-8e5d5',
    authDomain: 'notifikasi-project-8e5d5.firebaseapp.com',
    storageBucket: 'notifikasi-project-8e5d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzCfAD5cIW289kdyfoyLC26iZfcJVo7Yo',
    appId: '1:169765244214:android:c6950bd294403ce0aef797',
    messagingSenderId: '169765244214',
    projectId: 'notifikasi-project-8e5d5',
    storageBucket: 'notifikasi-project-8e5d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpbZtE5kZSwvrCfqT7xChzhioPd3jEKI',
    appId: '1:169765244214:ios:4385cfd587fa5ec2aef797',
    messagingSenderId: '169765244214',
    projectId: 'notifikasi-project-8e5d5',
    storageBucket: 'notifikasi-project-8e5d5.appspot.com',
    iosBundleId: 'com.example.simandorBarsel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpbZtE5kZSwvrCfqT7xChzhioPd3jEKI',
    appId: '1:169765244214:ios:4385cfd587fa5ec2aef797',
    messagingSenderId: '169765244214',
    projectId: 'notifikasi-project-8e5d5',
    storageBucket: 'notifikasi-project-8e5d5.appspot.com',
    iosBundleId: 'com.example.simandorBarsel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Ttk9YXF_HfHA1J5PrnwWgO7KmEMooFg',
    appId: '1:169765244214:web:8cab9c34c0df8a01aef797',
    messagingSenderId: '169765244214',
    projectId: 'notifikasi-project-8e5d5',
    authDomain: 'notifikasi-project-8e5d5.firebaseapp.com',
    storageBucket: 'notifikasi-project-8e5d5.appspot.com',
  );
}
